# Generated by Django 5.2 on 2025-05-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.TextField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('country', models.TextField(max_length=100, verbose_name='Country')),
            ],
        ),
    ]
