# Generated by Django 5.2 on 2025-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='info',
            name='gender',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
